// apps/playgrounds/solid-start/src/app.tsx
import { createSignal } from "solid-js";
import "./app.css";

export default function App() {
	const [count, setCount] = createSignal(0);

	return (
		<main>
			<h1>Hello world!</h1>
			<button
				class="increment"
				onClick={() => setCount(count() + 1)}
				type="button"
			>
				Clicks: {count()}
			</button>
			<p>
				Visit{" "}
				<a
					href="https://start.solidjs.com"
					target="_blank"
					rel="noopener noreferrer"
				>
					start.solidjs.com
				</a>{" "}
				to learn how to build SolidStart apps.
				<br />
				<br />
				<code>import.meta.env.VITE_TEST</code>:{" "}
				{String(import.meta.env.VITE_TEST)} (of type{" "}
				{typeof import.meta.env.VITE_TEST})
				<br />
				<code>import.meta.env.VITE_NUMERIC</code>:{" "}
				{String(import.meta.env.VITE_NUMERIC)} (of type{" "}
				{typeof import.meta.env.VITE_NUMERIC})
				<br />
				<code>import.meta.env.VITE_BOOLEAN</code>:{" "}
				{String(import.meta.env.VITE_BOOLEAN)} (of type{" "}
				{typeof import.meta.env.VITE_BOOLEAN})
			</p>
		</main>
	);
}

// apps/playgrounds/vite/src/App.tsx
import { useState } from "react";
import viteLogo from "/vite.svg";
import reactLogo from "./assets/react.svg";
import "./App.css";

function App() {
	const [count, setCount] = useState(0);

	return (
		<>
			<div>
				<a href="https://vite.dev" target="_blank" rel="noopener">
					<img src={viteLogo} className="logo" alt="Vite logo" />
				</a>
				<a href="https://react.dev" target="_blank" rel="noopener">
					<img src={reactLogo} className="logo react" alt="React logo" />
				</a>
			</div>
			<h1>Vite + React</h1>
			<div className="card">
				<button type="button" onClick={() => setCount((count) => count + 1)}>
					count is {count}
				</button>
				<p>
					Edit <code>src/App.tsx</code> and save to test HMR
				</p>
			</div>
			<p className="read-the-docs">
				Click on the Vite and React logos to learn more
			</p>
			<h1>My env vars</h1>
			<p>
				My var: {String(import.meta.env.VITE_MY_VAR)} (of type{" "}
				{typeof import.meta.env.VITE_MY_VAR})
			</p>
			<p>
				My number: {String(import.meta.env.VITE_MY_NUMBER)} (of type{" "}
				{typeof import.meta.env.VITE_MY_NUMBER})
			</p>
			<p>
				My boolean: {String(import.meta.env.VITE_MY_BOOLEAN)} (of type{" "}
				{typeof import.meta.env.VITE_MY_BOOLEAN})
			</p>
		</>
	);
}

export default App;
